function main(config) {
  config["proxy-groups"] = [
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Static.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      name: "PROXY",
      type: "select",
      proxies: ["DIRECT", "AUTO", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      name: "AUTO",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/OpenAI.png",
      "include-all": true,
      name: "AIGC",
      type: "select",
      proxies: ["PROXY", "AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Src/Icon/pikpak.svg",
      "include-all": true,
      name: "PikPak",
      type: "select",
      proxies: ["PROXY", "AUTO", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Src/Icon/pixiv.svg",
      "include-all": true,
      name: "PicHub",
      type: "select",
      proxies: ["PROXY", "AUTO", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png",
      "include-all": true,
      name: "Telegram",
      type: "select",
      proxies: ["PROXY", "AUTO", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Src/Icon/Applications.svg",
      "include-all": true,
      name: "应用程序代理",
      type: "select",
      proxies: ["PROXY", "AUTO", "REJECT", "DIRECT", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Google.png",
      "include-all": true,
      name: "Google",
      type: "select",
      proxies: ["PROXY", "AUTO", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/HK.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)香港|Hong Kong|HK|🇭🇰",
      name: "HK AUTO",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/SG.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)新加坡|Singapore|🇸🇬",
      name: "SG AUTO",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/JP.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)日本|Japan|🇯🇵",
      name: "JP AUTO",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/US.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)美国|USA|🇺🇸",
      name: "US AUTO",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png",
      "include-all": true,
      "exclude-filter": "(?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      name: "GLOBAL",
      type: "select",
      proxies: ["AUTO","DIRECT", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Src/Icon/AdobeCreativeCloud.svg",
      "include-all": false,
      name: "Adobe",
      type: "select",
      proxies: ["PROXY", "AUTO", "REJECT", "DIRECT"],
    },
    {
      icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/fish.svg",
      "include-all": true,
      name: "漏网之鱼",
      type: "select",
      proxies: ["PROXY", "AUTO", "REJECT", "DIRECT", "HK AUTO", "SG AUTO", "JP AUTO", "US AUTO"],
    },
  ];
  if (!config['rule-providers']) {
    config['rule-providers'] = {};
  }
  config["rule-providers"] = Object.assign(config["rule-providers"], {
    private: {
      url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.yaml",
      path: "./ruleset/Private_local.yaml",
      behavior: "domain",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    cn_domain: {
      url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.yaml",
      path: "./ruleset/cn_domain_local.yaml",
      behavior: "domain",
      interval: 86400,
      type: "http",
    },
    ai_GC: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/AIGC.yaml",
      path: "./ruleset/AIGC.yaml",
      behavior: "classical",
      interval: 86400,
      type: "http",
    },
    pikpakdomain: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/PikPak.yaml",
      path: "./ruleset/PikPak_local.yaml",
      behavior: "classical",
      interval: 86400,
      type: "http",
    },
    pic_hub: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/PiCHub.yaml",
      path: "./ruleset/PicHub_local.yaml",
      behavior: "classical",
      interval: 86400,
      type: "http",
    },
    google: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/Google.yaml",
      path: "./ruleset/Google_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    adobe: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/Adobe.yaml",
      path: "./ruleset/Adobe_local.yaml",
      behavior: "classical",
      interval: 86400,
      type: "http",
    },
    applications: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/applications.yaml",
      path: "./ruleset/Applications_local.yaml",
      behavior: "classical",
      interval: 86400,
      type: "http",
    },
    "geolocation-!cn": {
      url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.yaml",
      path: "./ruleset/geolocation-!cn.yaml",
      behavior: "domain",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    cn_ip: {
      url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.yaml",
      path: "./ruleset/cn_ip_local.yaml",
      behavior: "ipcidr",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    telegram: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/Telegram.yaml",
      path: "./ruleset/telegram_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    bing: {
      url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml",
      path: "./ruleset/bing_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    copilot: {
      url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.yaml",
      path: "./ruleset/copilot_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    claude: {
      url: "https://fastly.jsdelivr.net/gh/GJKen/clash-Rules@master/Rules/Claude.yaml",
      path: "./ruleset/claude_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    bard: {
      url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BardAI/BardAI.yaml",
      path: "./ruleset/bard_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    openai: {
      url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml",
      path: "./ruleset/openai_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    steam: {
      url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml",
      path: "./ruleset/steam_local.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
  });
  const customRules = [
    "DOMAIN-SUFFIX,cocogoat.work,DIRECT",
    "DOMAIN-KEYWORD,lgych,DIRECT",
    "DOMAIN-KEYWORD,webl,DIRECT",
    "DOMAIN-KEYWORD,tsdm,DIRECT",
    "DOMAIN-KEYWORD,ts-dm,PROXY",
    "DOMAIN-KEYWORD,v2rayse,PROXY",
    "DOMAIN-KEYWORD,nyaa,PROXY",
    "DOMAIN-KEYWORD,mojie,PROXY",
    "DOMAIN-SUFFIX,liyuans.com,PROXY",
    "DOMAIN-SUFFIX,xqc.best,PROXY",
    "DOMAIN-SUFFIX,adorarama.com,PROXY",
    "DOMAIN-SUFFIX,parklogic.com,PROXY",
    "DOMAIN-KEYWORD,rapidgator.net,PROXY",
    "DOMAIN-KEYWORD,frdl,PROXY",
    "DOMAIN-KEYWORD,dlsite,PicHub",
    "PROCESS-NAME,jianyingpro.exe,应用程序代理",
  ]
  config["rules"] = [
    ...customRules,
    // 这里是顺序匹配,如果匹配到规则则停止下一个匹配
    "RULE-SET,private,DIRECT",
    "RULE-SET,applications,应用程序代理",
    "RULE-SET,adobe,Adobe",
    "RULE-SET,pic_hub,PicHub",
    "RULE-SET,steam,PROXY",
    "RULE-SET,google,Google",
    "RULE-SET,claude,AIGC",
    "RULE-SET,ai_GC,AIGC",
    "RULE-SET,pikpakdomain,PikPak",
    "RULE-SET,telegram,Telegram",
    "RULE-SET,geolocation-!cn,PROXY",
    "RULE-SET,cn_domain,DIRECT",
    "RULE-SET,cn_ip,DIRECT",
    "MATCH,漏网之鱼"
  ];
  return config;
}